apiVersion: apps/v1
kind: Deployment
metadata:
  name: lloyds-azure-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lloydsazure
  template:
    metadata:
      labels:
        app: lloydsazure

        pool: my-new-agent-lloyds

    spec:
      containers:
        - name: lloydsazure
          image: lloydsrepo.azurecr.io/lloyds-demo-app:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          resources:
           requests:
            memory: "64Mi"
            cpu: 1m
           limits:
            memory: "128Mi"
            cpu: 1000m


# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lloydsazure
    k8s-app: lloydsazure
  name: lloydsazure
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: lloydsazure