apiVersion: apps/v1
kind: Deployment
metadata:
  name: lloyds-azure-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lloydsazure
  template:
    metadata:
      labels:
        app: lloydsazure

        pool: my-personal-computer

    spec:
      containers:
        - name: lloydsazure
          image: lloydsrepo.azurecr.io/paulvy321321/LLoydsBankAzure:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lloydsazure
    k8s-app: lloydsazure
  name: lloydsazure
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: lloydsazure