apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lloyds-azure-deployment
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lloyds-azure-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20